#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Math-Calc-Units
Version  : 1.07
Release  : 22
URL      : https://cpan.metacpan.org/authors/id/S/SF/SFINK/Math-Calc-Units-1.07.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/S/SF/SFINK/Math-Calc-Units-1.07.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libm/libmath-calc-units-perl/libmath-calc-units-perl_1.07-2.debian.tar.xz
Summary  : ~
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0 GPL-2.0
Requires: perl-Math-Calc-Units-bin = %{version}-%{release}
Requires: perl-Math-Calc-Units-license = %{version}-%{release}
Requires: perl-Math-Calc-Units-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
Examples:
It won't take *that* long to download this 650MB cd image over Mom's
33.6Kbps modem, will it? I can just let it run all night.

%package bin
Summary: bin components for the perl-Math-Calc-Units package.
Group: Binaries
Requires: perl-Math-Calc-Units-license = %{version}-%{release}

%description bin
bin components for the perl-Math-Calc-Units package.


%package dev
Summary: dev components for the perl-Math-Calc-Units package.
Group: Development
Requires: perl-Math-Calc-Units-bin = %{version}-%{release}
Provides: perl-Math-Calc-Units-devel = %{version}-%{release}
Requires: perl-Math-Calc-Units = %{version}-%{release}

%description dev
dev components for the perl-Math-Calc-Units package.


%package license
Summary: license components for the perl-Math-Calc-Units package.
Group: Default

%description license
license components for the perl-Math-Calc-Units package.


%package perl
Summary: perl components for the perl-Math-Calc-Units package.
Group: Default
Requires: perl-Math-Calc-Units = %{version}-%{release}

%description perl
perl components for the perl-Math-Calc-Units package.


%prep
%setup -q -n Math-Calc-Units-1.07
cd %{_builddir}
tar xf %{_sourcedir}/libmath-calc-units-perl_1.07-2.debian.tar.xz
cd %{_builddir}/Math-Calc-Units-1.07
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/Math-Calc-Units-1.07/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Math-Calc-Units
cp %{_builddir}/Math-Calc-Units-1.07/COPYING %{buildroot}/usr/share/package-licenses/perl-Math-Calc-Units/b7db613f1590a02fd8544d4253d0201a88f0b919
cp %{_builddir}/Math-Calc-Units-1.07/LICENSE %{buildroot}/usr/share/package-licenses/perl-Math-Calc-Units/5a42859d23b7f1571dc1e9bedb33669a5c6f9c0c
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-Math-Calc-Units/3c1f182c50bd8369f72f36d256b4e0194d2b7a89
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ucalc

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Math::Calc::Units.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Math-Calc-Units/3c1f182c50bd8369f72f36d256b4e0194d2b7a89
/usr/share/package-licenses/perl-Math-Calc-Units/5a42859d23b7f1571dc1e9bedb33669a5c6f9c0c
/usr/share/package-licenses/perl-Math-Calc-Units/b7db613f1590a02fd8544d4253d0201a88f0b919

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
