#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Math-Calc-Units
Version  : 1.07
Release  : 2
URL      : https://cpan.metacpan.org/authors/id/S/SF/SFINK/Math-Calc-Units-1.07.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/S/SF/SFINK/Math-Calc-Units-1.07.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libm/libmath-calc-units-perl/libmath-calc-units-perl_1.07-2.debian.tar.xz
Summary  : ~
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0 GPL-2.0
Requires: perl-Math-Calc-Units-bin = %{version}-%{release}
Requires: perl-Math-Calc-Units-license = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
Examples:
It won't take *that* long to download this 650MB cd image over Mom's
33.6Kbps modem, will it? I can just let it run all night.

%package bin
Summary: bin components for the perl-Math-Calc-Units package.
Group: Binaries
Requires: perl-Math-Calc-Units-license = %{version}-%{release}

%description bin
bin components for the perl-Math-Calc-Units package.


%package dev
Summary: dev components for the perl-Math-Calc-Units package.
Group: Development
Requires: perl-Math-Calc-Units-bin = %{version}-%{release}
Provides: perl-Math-Calc-Units-devel = %{version}-%{release}

%description dev
dev components for the perl-Math-Calc-Units package.


%package license
Summary: license components for the perl-Math-Calc-Units package.
Group: Default

%description license
license components for the perl-Math-Calc-Units package.


%prep
%setup -q -n Math-Calc-Units-1.07
cd ..
%setup -q -T -D -n Math-Calc-Units-1.07 -b 1
mkdir -p deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Math-Calc-Units-1.07/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Math-Calc-Units
cp COPYING %{buildroot}/usr/share/package-licenses/perl-Math-Calc-Units/COPYING
cp LICENSE %{buildroot}/usr/share/package-licenses/perl-Math-Calc-Units/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.26.1/Math/Calc/Units.pm
/usr/lib/perl5/vendor_perl/5.26.1/Math/Calc/Units/Compute.pm
/usr/lib/perl5/vendor_perl/5.26.1/Math/Calc/Units/Convert.pm
/usr/lib/perl5/vendor_perl/5.26.1/Math/Calc/Units/Convert/Base.pm
/usr/lib/perl5/vendor_perl/5.26.1/Math/Calc/Units/Convert/Base2Metric.pm
/usr/lib/perl5/vendor_perl/5.26.1/Math/Calc/Units/Convert/Byte.pm
/usr/lib/perl5/vendor_perl/5.26.1/Math/Calc/Units/Convert/Combo.pm
/usr/lib/perl5/vendor_perl/5.26.1/Math/Calc/Units/Convert/Date.pm
/usr/lib/perl5/vendor_perl/5.26.1/Math/Calc/Units/Convert/Distance.pm
/usr/lib/perl5/vendor_perl/5.26.1/Math/Calc/Units/Convert/Metric.pm
/usr/lib/perl5/vendor_perl/5.26.1/Math/Calc/Units/Convert/Multi.pm
/usr/lib/perl5/vendor_perl/5.26.1/Math/Calc/Units/Convert/Time.pm
/usr/lib/perl5/vendor_perl/5.26.1/Math/Calc/Units/Grammar.pm
/usr/lib/perl5/vendor_perl/5.26.1/Math/Calc/Units/Grammar.y
/usr/lib/perl5/vendor_perl/5.26.1/Math/Calc/Units/Rank.pm

%files bin
%defattr(-,root,root,-)
/usr/bin/ucalc

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Math::Calc::Units.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Math-Calc-Units/COPYING
/usr/share/package-licenses/perl-Math-Calc-Units/LICENSE
